version: '2'
services:
  data:
    image: postgres:9.6
    container_name: "matcha_data"
    volumes:
      - /data/db
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - DEBUG=true
      - POSTGRES_DB=matcha
      - POSTGRES_USER=Gus
      - POSTGRES_PASSWORD=yolo
