export const FETCH_THREADS_REQUEST = 'FETCH_THREADS_REQUEST'
export const FETCH_THREADS_SUCCESS = 'FETCH_THREADS_SUCCESS'
export const FETCH_THREADS_FAILURE = 'FETCH_THREADS_FAILURE'

export const GET_CHAT_REQUEST = 'GET_CHAT_REQUEST'
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'
export const GET_CHAT_FAILURE = 'GET_CHAT_FAILURE'

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE'
