export const FETCH_PICTURES_REQUEST = 'FETCH_PICTURES_REQUEST'
export const FETCH_PICTURES_SUCCESS = 'FETCH_PICTURES_SUCCESS'
export const FETCH_PICTURES_FAILURE = 'FETCH_PICTURES_FAILURE'

export const UPLOAD_PICTURE_REQUEST = 'UPLOAD_PICTURE_REQUEST'
export const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS'
export const UPLOAD_PICTURE_FAILURE = 'UPLOAD_PICTURE_FAILURE'

export const DELETE_PICTURE_REQUEST = 'DELETE_PICTURE_REQUEST'
export const DELETE_PICTURE_SUCCESS = 'DELETE_PICTURE_SUCCESS'
export const DELETE_PICTURE_FAILURE = 'DELETE_PICTURE_FAILURE'

export const PROFIL_PICTURE_SUCCESS = 'PROFIL_PICTURE_SUCCESS'
export const PROFIL_PICTURE_FAILURE = 'PROFIL_PICTURE_FAILURE'

export const EMPTY_PICTURE = 'http://localhost:8000/files/assets/empty_avatar.jpg'
