export const FETCH_PROFIL_REQUEST = 'FETCH_PROFIL_REQUEST'
export const FETCH_PROFIL_SUCCESS = 'FETCH_PROFIL_SUCCESS'
export const FETCH_PROFIL_FAILURE = 'FETCH_PROFIL_FAILURE'

export const UPDATE_PROFIL_REQUEST = 'UPDATE_PROFIL_REQUEST'
export const UPDATE_PROFIL_SUCCESS = 'UPDATE_PROFIL_SUCCESS'
export const UPDATE_PROFIL_FAILURE = 'UPDATE_PROFIL_FAILURE'

export const GET_PROFIL_REQUEST = 'GET_PROFIL_REQUEST'
export const GET_PROFIL_SUCCESS = 'GET_PROFIL_SUCCESS'
export const GET_PROFIL_FAILURE = 'GET_PROFIL_FAILURE'

export const GET_PROFILS_REQUEST = 'GET_PROFILS_REQUEST'
export const GET_PROFILS_SUCCESS = 'GET_PROFILS_SUCCESS'
export const GET_PROFILS_FAILURE = 'GET_PROFILS_FAILURE'

export const LIKE_PROFIL_REQUEST = 'LIKE_PROFIL_REQUEST'
export const LIKE_PROFIL_SUCCESS = 'LIKE_PROFIL_SUCCESS'
export const LIKE_PROFIL_FAILURE = 'LIKE_PROFIL_FAILURE'
