export const FETCH_PROFIL_REQUEST = 'FETCH_PROFIL_REQUEST'
export const FETCH_PROFIL_SUCCESS = 'FETCH_PROFIL_SUCCESS'
export const FETCH_PROFIL_FAILURE = 'FETCH_PROFIL_FAILURE'

export const UPDATE_PROFIL_REQUEST = 'UPDATE_PROFIL_REQUEST'
export const UPDATE_PROFIL_SUCCESS = 'UPDATE_PROFIL_SUCCESS'
export const UPDATE_PROFIL_FAILURE = 'UPDATE_PROFIL_FAILURE'
