export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE'

export const TAG_OPERATION_REQUEST = 'TAG_OPERATION_REQUEST'
export const TAG_OPERATION_SUCCESS = 'TAG_OPERATION_SUCCESS'
export const TAG_OPERATION_FAILURE = 'TAG_OPERATION_FAILURE'
