const errors = {
  EMAIL_MISSING: 'EMAIL_MISSING',
  EMAIL_EXIST: 'EMAIL_EXIST',
  PASSWORD_MISSING: 'PASSWORD_MISSING',
  PASSWORD_TO_SHORT: 'PASSWORD_TO_SHORT',
  TYPE_MISSING: 'TYPE_MISSING',
  PSEUDO_MISSING: 'PSEUDO_MISSING',
  PSEUDO_EXIST: 'PSEUDO_EXIST',
  INTRNAL_ERROR: 'INTRNAL_ERROR',
  LOGIN_UNKNOWN_PSEUDO: 'LOGIN_UNKNOWN_PSEUDO',
  LOGIN_BAD_PASSWORD: 'LOGIN_BAD_PASSWORD'
}

module.exports = errors
