const errors = {
  EMAIL_MISSING: 'EMAIL_MISSING',
  EMAIL_EXIST: 'EMAIL_EXIST',
  PASSWORD_MISSING: 'PASSWORD_MISSING',
  PASSWORD_TO_SHORT: 'PASSWORD_TO_SHORT',
  TYPE_MISSING: 'TYPE_MISSING',
  PSEUDO_MISSING: 'PSEUDO_MISSING',
  PSEUDO_EXIST: 'PSEUDO_EXIST',
  INTRNAL_ERROR: 'INTRNAL_ERROR',
  LOGIN_UNKNOWN_PSEUDO: 'LOGIN_UNKNOWN_PSEUDO',
  LOGIN_BAD_PASSWORD: 'LOGIN_BAD_PASSWORD',
  TOKEN_NOT_PROVIDED: 'TOKEN_NOT_PROVIDED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  BAD_PICTURE_SIGNATURE: 'BAD_PICTURE_SIGNATURE',
  PICTURE_EMPTY_FILE: 'PICTURE_EMPTY_FILE',
  PICTURE_NO_MIMETYPE: 'PICTURE_NO_MIMETYPE',
  PICTURE_BAD_SERVER_UPLOAD: 'PICTURE_BAD_SERVER_UPLOAD',
  PICTURE_CANT_GET_SIZE: 'PICTURE_CANT_GET_SIZE',
  PICTURE_EMPTY_INDEX: 'PICTURE_EMPTY_INDEX',
  PICTURE_BAD_INDEX: 'PICTURE_BAD_INDEX'
}

module.exports = errors
