const errors = {
  EMAIL_MISSING: 'EMAIL_MISSING',
  PASSWORD_MISSING: 'PASSWORD_MISSING',
  PASSWORD_TO_SHORT: 'PASSWORD_TO_SHORT',
  TYPE_MISSING: 'TYPE_MISSING',
  PSEUDO_MISSING: 'PSEUDO_MISSING'
}

module.exports = errors
